### ISSUE TITLE
UTF-8 characters

### ISSUE THREAD

**Issue by MarianMichalovic** [wso2/jaggery#1]
Hello,
Jaggery I tried first time. I have a problem with UTF-8 characters.
Characters e.g. á, ú, č, š incorrectly displays.
Thanks.

**Comment by zhoudegao** [comment]
Hi, 
We are trying to use jaggeryjs framework in our project. It seems that it still can not support unicode character, like chinese?

**Comment by muluer** [comment]
still open @ 5 Sep 2016 !!!
