### ISSUE TITLE
trivial Suggestion - documentation scroll persistence

### ISSUE THREAD

**Issue by vasanthkumarmvp** [wso2/jaggery#170]
Hi,

I recently came across jaggery and going through it, its cool.
Here when i read through the documentation (syntax and built-ins), i have to scroll down every time to go on the next article. Either my selection should persist in the list or a next button would be helpful.

Thanks!
Vasanth

**Comment by NipunaMarcus** [comment]
We will look in to a prefer method to make this easy... Thank you for pointing this out.
